### ISSUE TITLE
Error message doesn't display instantly!

### ISSUE THREAD

**Issue by mazyar-cyber** [dive-be/laravel-dry-requests#1]
I have install package and use it's trait in the form request class but it is not work in the front

**Comment by mabdullahsari** [comment]
Hey,

It might not have been clear to you, but making a request `DryRunnable` is not sufficient. This package is FE framework agnostic, so it will require a bit more work by your side. You should instruct your Http client on the FE to send a request as a dry request (see docs) so your Laravel back-end can act accordingly. In other words, the way you display and use the errors is completely up to you. For this, I'm referring you to the documentation of your favorite FE framework.

I have also included an example for Inertia.js using React, so you can base it off of that too.
